/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws IOException {

//      API: http://swquotesapi.digitaljedi.dk/api/SWQuote/RandomStarWarsQuote

        URL url = new URL("http://swquotesapi.digitaljedi.dk/api/SWQuote/RandomStarWarsQuote");

        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setRequestMethod("GET");
        int responseCode = connection.getResponseCode();


//      FEATURE 2 ::: if API call fails it displays from the file (code already written)

        if (responseCode != 200) {   // check for good response

//      ----- API CALL FAILED :: Quote From File -----
            try { // help from https://attacomsian.com/blog/gson-read-json-file

                Gson gson = new Gson();
                Reader reader = Files.newBufferedReader(Paths.get("src/main/resources/quotes.json"));
                Quotes[] offlineQuoteFile = gson.fromJson(reader, Quotes[].class);

                int randomNumber = randomNumber();
                System.out.println( offlineQuoteFile[randomNumber] );

                reader.close();

            } catch (Exception ex) {
                ex.printStackTrace();
            }

        } else {

//      ------ Star Wars API ::: Random Quote -----

            BufferedReader input = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            String oneLine = input.readLine();
            StringBuffer entireStringFromResponse = new StringBuffer();

            while (oneLine != null){
                entireStringFromResponse.append(oneLine);
                oneLine = input.readLine();
            }

//            deserialize into java object with exact key value pair names

            input.close();
            String quoteToConstruct = String.valueOf(entireStringFromResponse);


            Gson g = new Gson();
            QuoteApi q = g.fromJson(quoteToConstruct, QuoteApi.class);

//      ---- saves single file ----

            FileWriter save = new FileWriter("src/main/resources/savedStarWarsQuote.json");
            g.toJson(quoteToConstruct,save);
            save.close();

            System.out.println(q);

//      convert quotes.json into array list -> add to array list
//            ---------------------------------------
//            ArrayList quoteList = new ArrayList<>();
//            quoteList = gson.fromJson(quotesJSON, new TypeToken>(){}.getType());

        }

//      after pulling quote from API save it to the Json

    }

    public static int randomNumber () {
        int min = 0;
        int max = 138;

        return (int) (Math.random() * (max - min + 1) + min);
    }
}
